const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      slug: 'shirt2',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      slug: 'shirt3',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      slug: 'shirt4',
      category: 'Shirts',
      image: '/images/shirt4.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pants1',
      slug: 'pants1',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'YUP',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pants2',
      slug: 'pants2',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Something British',
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};

export default data;
